import { RouteInfo } from "./sidebar.metadata";
export const ROUTES: RouteInfo[] = [
  {
    path: "",
    title: "SAP Support",
    iconType: "feather",
    icon: "pen-tool",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [
      {
        path: "dashboard",
        title: "Dashboard",
        iconType: "feather",
        icon: "bar-chart-2",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
      {
        path: "requirements",
        title: "Requirements",
        iconType: "feather",
        icon: "align-left",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
      // {
      //   path: "",
      //   title: "Test",
      //   iconType: "feather",
      //   icon: "",
      //   class: "ml-sub-menu",
      //   groupTitle: false,
      //   badge: "",
      //   badgeClass: "",
      //   submenu: [
      //     {
      //       path: "testcycles",
      //       title: "Cycles",
      //       iconType: "feather",
      //       icon: "refresh-cw",
      //       class: "ml-menu2",
      //       groupTitle: false,
      //       badge: "",
      //       badgeClass: "",
      //       submenu: [],
      //     },
      //     {
      //       path: "testscenarios",
      //       title: "Scenarios",
      //       iconType: "feather",
      //       icon: "wind",
      //       class: "ml-menu2",
      //       groupTitle: false,
      //       badge: "",
      //       badgeClass: "",
      //       submenu: [],
      //     },
      //     {
      //       path: "testcases",
      //       title: "Cases",
      //       iconType: "feather",
      //       icon: "message-square",
      //       class: "ml-menu2",
      //       groupTitle: false,
      //       badge: "",
      //       badgeClass: "",
      //       submenu: [],
      //     },
      //   ],
      // },
      {
        path: "bugs",
        title: "Bugs",
        iconType: "feather",
        icon: "trello",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
    ],
  },
  {   
        path: '/authentication/login',
        title: 'Log In',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
  },
  {   
    path: '/authentication/register',
    title: 'Register',
    iconType: '',
    icon: '',
    class: 'ml-menu',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
},
  // {
  //   path: "dashboard",
  //   title: "Dashboard",
  //   iconType: "feather",
  //   icon: "home",
  //   class: "",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   submenu: [],
  // },
  // {
  //   path: "requirements",
  //   title: "Requirements",
  //   iconType: "feather",
  //   icon: "align-left",
  //   class: "",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   submenu: [],
  // },
  // {
  //   path: "",
  //   title: "Test",
  //   iconType: "feather",
  //   icon: "pen-tool",
  //   class: "menu-toggle",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   submenu: [
  //     {
  //       path: "testcycles",
  //       title: "Cycles",
  //       iconType: "feather",
  //       icon: "refresh-cw",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       submenu: [],
  //     },
  //     {
  //       path: "testscenarios",
  //       title: "Scenarios",
  //       iconType: "feather",
  //       icon: "wind",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       submenu: [],
  //     },
  //     {
  //       path: "testcases",
  //       title: "Cases",
  //       iconType: "feather",
  //       icon: "message-square",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       submenu: [],
  //     },
  //   ],
  // },
  // {
  //   path: "bugs",
  //   title: "Bugs",
  //   iconType: "feather",
  //   icon: "trello",
  //   class: "",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   submenu: [],
  // },
];

export const ROUTESW: RouteInfo[] = [
  {
    path: "dashboard",
    title: "Dashboard",
    iconType: "feather",
    icon: "home",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  {
    path: "requirements",
    title: "Requirements",
    iconType: "feather",
    icon: "align-left",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  // {
  //   path: "testcycles",
  //   title: "Test > Cycles",
  //   iconType: "feather",
  //   icon: "list",
  //   class: "",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   submenu: [],
  // },
  // {
  //   path: "testscenarios",
  //   title: "Test > Scenarios",
  //   iconType: "feather",
  //   icon: "list",
  //   class: "",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   submenu: [],
  // },
  // {
  //   path: "testcases",
  //   title: "Test > Cases",
  //   iconType: "feather",
  //   icon: "list",
  //   class: "",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   submenu: [],
  // },
  {
    path: "bugs",
    title: "Bugs",
    iconType: "feather",
    icon: "trello",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  {
    path: "usermanagement",
    title: "Settings > User Management",
    iconType: "feather",
    icon: "",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  // {
  //   path: "companymanagement",
  //   title: "Settings > Company Management",
  //   iconType: "feather",
  //   icon: "",
  //   class: "",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   submenu: [],
  // },
  // {
  //   path: "projects",
  //   title: "Settings > Projects",
  //   iconType: "feather",
  //   icon: "",
  //   class: "",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   submenu: [],
  // },
];

export const SETTINGS: RouteInfo[] = [
  {
    path: "usermanagement",
    title: "User Management",
    iconType: "feather",
    icon: "",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  // {
  //   path: "companymanagement",
  //   title: "Company Management",
  //   iconType: "feather",
  //   icon: "",
  //   class: "",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   submenu: [],
  // },
  // {
  //   path: "projects",
  //   title: "Projects",
  //   iconType: "feather",
  //   icon: "",
  //   class: "",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   submenu: [],
  // },
];
